"""Query rewriting for multi-query retrieval expansion.

A single user question often phrases a concept differently from the course
slides, so a lone dense query can miss relevant chunks. Expanding the question
into a few diverse paraphrases / sub-questions and retrieving for each one
widens recall before fusion. This is an opt-in recall booster: it never changes
the refusal guard, which is still applied after fusion in the retrieval layer.

The expansion is best-effort. The LLM call is wrapped so any failure (provider
error, malformed output) degrades gracefully to just the original question
rather than raising, keeping retrieval available even when rewriting fails.
"""

from core.llm import get_llm
from core.obs import get_callbacks

_SYSTEM = (
    "You rewrite a student's question into diverse search queries for a course "
    "retrieval system.\n"
    "- Produce up to {n} alternative phrasings or focused sub-questions.\n"
    "- Keep the same language and the course's own terminology.\n"
    "- Cover synonyms and related angles so retrieval recall improves.\n"
    "- Output one query per line, plain text, no numbering, no extra commentary."
)

_HYDE_SYSTEM = (
    "You write a short, plausible textbook passage that would answer a student's "
    "course question.\n"
    "- Write 2-4 sentences in the same language as the question.\n"
    "- Use the kind of terminology and definitions a course would use.\n"
    "- This is a hypothetical retrieval probe, not a final answer: do not add "
    "citations, headings, or any commentary, just the passage text."
)


def _parse_rewrites(raw: str) -> list[str]:
    """Extract clean rewrite lines from the raw LLM output.

    Tolerates common list formatting (leading bullets, ``1.`` numbering) and
    blank lines. Returns the stripped, non-empty lines in order.
    """
    rewrites: list[str] = []
    for line in raw.splitlines():
        cleaned = line.strip().lstrip("-*•").strip()
        # Drop a leading "1." / "2)" style enumerator if the model added one.
        if cleaned[:1].isdigit():
            for sep in (".", ")", ":"):
                head, found, tail = cleaned.partition(sep)
                if found and head.strip().isdigit():
                    cleaned = tail.strip()
                    break
        if cleaned:
            rewrites.append(cleaned)
    return rewrites


def _dedupe(queries: list[str]) -> list[str]:
    """Drop case-insensitive duplicates while preserving first-seen order."""
    seen: set[str] = set()
    out: list[str] = []
    for q in queries:
        key = q.casefold()
        if key not in seen:
            seen.add(key)
            out.append(q)
    return out


def expand_query(question: str, n: int = 3, api_key: str | None = None) -> list[str]:
    """Return the original question plus up to ``n`` LLM-generated rewrites.

    Asks the small ``router`` LLM for diverse paraphrases / sub-questions, then
    returns ``[question, *rewrites]`` de-duplicated (case-insensitive,
    order-preserving). The original always comes first so the primary query is
    never lost.

    ``api_key`` is an optional per-request OpenAI key forwarded to ``get_llm``:
    when set, the rewrite call runs on the visitor's own OpenAI model (see
    :func:`core.llm.get_llm`); when None the configured free model is used.

    Robust by construction: any error from the model, or output that yields no
    usable rewrites, falls back to ``[question]``. This function never raises,
    so the retrieval layer can call it unconditionally on the multi-query path.
    """
    if n <= 0:
        return [question]

    try:
        raw = (
            get_llm("router", api_key=api_key)
            .invoke(
                [
                    ("system", _SYSTEM.format(n=n)),
                    ("human", question),
                ],
                config={"callbacks": get_callbacks()},
            )
            .content
        )
    except Exception:
        # Provider/transport failure: degrade to the original question only.
        return [question]

    if not isinstance(raw, str):
        return [question]

    rewrites = _parse_rewrites(raw)[:n]
    return _dedupe([question, *rewrites])


def hyde_passage(question: str, api_key: str | None = None) -> str:
    """Return a hypothetical answer passage for the question (HyDE probe).

    Asks the small ``router`` LLM to write a short, plausible course passage
    that *would* answer the question. Embedding this hypothetical answer instead
    of the bare question often lands closer to the relevant chunks in vector
    space, because an answer resembles the indexed material more than a question
    does (Hypothetical Document Embeddings).

    ``api_key`` is an optional per-request OpenAI key forwarded to ``get_llm``:
    when set, the probe is generated by the visitor's own OpenAI model; when None
    the configured free model is used.

    Robust by construction: any error from the model, non-string output, or an
    empty/blank passage falls back to the original ``question``. This function
    never raises, so the retrieval layer can call it unconditionally on the HyDE
    path. Falling back to the question means HyDE degrades to a plain dense query
    rather than failing, and the refusal guard downstream is unaffected.
    """
    try:
        raw = (
            get_llm("router", api_key=api_key)
            .invoke(
                [
                    ("system", _HYDE_SYSTEM),
                    ("human", question),
                ],
                config={"callbacks": get_callbacks()},
            )
            .content
        )
    except Exception:
        # Provider/transport failure: degrade to the original question.
        return question

    if not isinstance(raw, str):
        return question

    passage = raw.strip()
    return passage or question
